CREATE DATABASE `doingsdone`

USE `doingsdone`

CREATE TABLE user (
id INT NOT NULL AUTO_INCREMENT,
dateRegistration TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(100) NOT NULL,
name VARCHAR(50) NOT NULL,
password VARCHAR(255) NOT NULL,
PRIMARY KEY (id),
INDEX uName (name),
UNIQUE INDEX (email)
) ENGINE=InnoDB

